# storage configuration
Storage:
#  storage type. Available types are: inmemory, redis, sqlite, mysql, postgresql
  type: redis
  tableName: delayer
  host: localhost
  port: 6379
  user: user
  password: password
