name: Delayer
main: me.veritaris.delayer.Delayer
author: Veritaris
load: STARTUP
authors: [Veritaris]
website: https://dreamfinity.org
version: 1.2.2
commands:
  delay:
    aliases: [delay]

permissions:
  delay.*:
    description: Возможность использовать все команды плагина
    children:
      delay.set: true
      delay.remove: true
      delay.list: true
      delay.help: true
  delay.set:
    description: Возможность установить команду для игрока
    default: false
  delay.remove:
    description: Возможность удалять назначенную команду
    default: false
  delay.list:
    description: Возможность просматривать назначенные игрокам команды
    default: false
  delay.help:
    description: Возможность просматривать помощь по плагину
    default: true
